spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true
    locations: classpath:db/migration

  resilience4j:
    circuitbreaker:
      instances:
        priceService:
          sliding-window-size: 10
          minimum-successful-calls: 4
          failure-rate-threshold: 50
          wait-duration-in-open-state: 10s
    retry:
      instances:
        priceRepository:
          max-attempts: 2
          wait-duration: 500ms

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000, expireAfterAccess=10m


