openapi: 3.0.0
info:
  title: Product Pricing API
  version: 1.0.0
  description: API for querying applicable prices for products in a retail chain.

servers:
  - url: http://localhost:8080/api/v1

paths:
  /prices/applicable:
    get:
      summary: Get applicable price for a product
      description: |
        Retrieves the applicable price for a product in a retail chain based on the provided application date.
      parameters:
        - name: applicationDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
          description: The date and time when the price is applicable (e.g., '2024-08-26T15:00:00').
        - name: productId
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: The ID of the product.
        - name: brandId
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: The ID of the brand.
      responses:
        '200':
          description: Applicable price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '404':
          description: No applicable price found for the provided parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Invalid input parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: getApplicablePrice

components:
  schemas:
    Price:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: The ID of the product code.
        priceList:
          type: integer
          format: int64
          description: The ID of the applicable price list.
        startDate:
          type: string
          format: date-time
          description: The start date of the price's validity.
        endDate:
          type: string
          format: date-time
          description: The end date of the price's validity.
        price:
          type: number
          format: double
          description: The final price to apply.
        currency:
          type: string
          description: The currency code (e.g., 'EUR').
        brandId:
          type: integer
          format: int64
          description: The ID of the brand (e.g., 1 for ZARA).

    PriceResponse:
      type: object
      properties:
        price:
          $ref: '#/components/schemas/Price'

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: A descriptive message explaining the error.
        errorCode:
          type: string
          description: A code representing the type of error.